apiVersion: apps/v1
kind: Deployment
metadata:
  name: producer-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: producer-service
  template:
    metadata:
      labels:
        app: producer-service
    spec:
      containers:
        - name: producer-service
          image: producer-service:local
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: producer-service
spec:
  selector:
    app: producer-service
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: producer-service-config
data:
  spring.application.name: producer-service
  server.port: "8080"
  spring.rabbitmq.host: rabbitmq
  spring.rabbitmq.port: "5672"
  spring.rabbitmq.username: seckinguzel
  spring.rabbitmq.password: seckinguzel
  sr.rabbit.queue.name: seckinguzel-queue
  sr.rabbit.routing.name: seckinguzel-routing
  sr.rabbit.exchange.name: seckinguzel-exchange
