apiVersion: v2
name: producer-service
description: A Helm chart for the producer-service microservice
type: application
version: 1.0.0
appVersion: "1.0"

serviceAccount:
  create: true
  name: ""

dependencies:
  - name: rabbitmq
    version: 8.17.0
    repository: https://charts.bitnami.com/bitnami

image:
  repository: myregistry/producer-service
  tag: latest

service:
  port: 8080
  type: NodePort

rabbitmq:
  host: rabbitmq
  port: 5672
  username: seckinguzel
  password: seckinguzel
  queueName: seckinguzel-queue
  routingName: seckinguzel-routing
  exchangeName: seckinguzel-exchange

ingress:
  enabled: false

autoscaling:
  enabled: false
